force-app/main/default/objects/Town_Distance__c/Town_Distance__c.object-meta.xml
<CustomObject>
    <description>A junction object that calculates the distance between two towns</description>
    <label>Town Distance</label>
    <nameField>
        <label>Town Distance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Town Distances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Town_Distance__c/fields/Driving_Distance_Km__c.field-meta.xml
<CustomField>
    <fullName>Driving_Distance_Km__c</fullName>
    <inlineHelpText>This is the driving distance according to Bing Maps. Can also be manually added</inlineHelpText>
    <label>Driving Distance (Km)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Town_Distance__c/fields/Start_End__c.field-meta.xml
<CustomField>
    <fullName>Start_End__c</fullName>
    <formula>IF( Starting_Town__c =  Destination__c, TRUE, FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start = End</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Town_Distance__c/fields/UpdateDateTime__c.field-meta.xml
<CustomField>
    <fullName>UpdateDateTime__c</fullName>
    <description>Used when triggering the Apex class that calculates the driving distance. Udating this field will trigger the integration to run</description>
    <label>UpdateDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/UpdateTownDistanceSchedule.cls
global class UpdateTownDistanceSchedule implements Schedulable {

    global void execute(SchedulableContext sc) {
        updateTownDistances();
    }

    @future
    public static void updateTownDistances() {
        List<Town_Distance__c> townDistancesToUpdate = [
            SELECT Id, UpdateDateTime__c
            FROM Town_Distance__c
            WHERE Driving_Distance_Km__c = null
            AND Start_End__c = false
            LIMIT 100
        ];

        if (!townDistancesToUpdate.isEmpty()) {
            for (Town_Distance__c td : townDistancesToUpdate) {
                td.UpdateDateTime__c = System.now();
            }
            update townDistancesToUpdate;
        }
    }
}